---
- hosts: localhost
  tasks:
  - name: "get image"
    docker_image:
      name: 192.168.33.10:5000/user
      tag: 2
      repository: 192.168.33.10:5000/user
  - name: "start container"
    docker_container:
      name: user
      image: 192.168.33.10:5000/user:2
      published_ports:
      - "8080:8080"
      env:
        TAG: a2bd4e
      command:
        "--spring.profiles.active=dev"
